version: 0.2

phases:
  install:
    commands:
      - "apt update"
      - "apt install unzip openjdk-8-jdk -y"
      - "wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip"
      - "unzip terraform_0.13.5_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - TEMP_ROLE=`aws sts assume-role --role-arn ${assume_role_arn} --role-session-name test --duration-seconds 900 --region ${region} --endpoint-url https://sts.${region}.amazonaws.com`
      - export TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - terraform init
      - terraform workspace select ${TF_VAR_ENVIRONMENT} || terraform workspace new ${TF_VAR_ENVIRONMENT}

  build:
    commands:
      - mvn package
      - terraform $TF_COMMAND --auto-approve

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on `date`
